### ISSUE TITLE
Delete all non-existing schedules on deploy

### ISSUE THREAD

**Issue by magnusnyborgmoan** [cognitedata/function-action#9]
Currently, when the action is run on a "push" the following will be done to handle schedule deployments:

For each schedule mentioned in the config file:

1. Delete any existing schedules with the name of the current schedule
2. Recreate the schedule

This is however flawed, as this will not delete a schedule that's no longer exists in the config file. A new and better flow would be:

1. Before deploying any schedules, delete all existing schedules
2. For each schedule mentioned in the config file: Deploy

To make these updates one would have to update `index.py` and `schedules.py`.

**Comment by pavelzubarev** [comment]
should be resolved with v2 tag action
